#!/bin/bash
# Quick links to check Discovery Engine datastores

PROJECT_ID="ai-testing-458318"

echo "=================================="
echo "Discovery Engine Datastore Links"
echo "=================================="
echo ""
echo "Open these URLs in your browser to check datastore status:"
echo ""
echo "1. Gmail Datastore:"
echo "   https://console.cloud.google.com/gen-app-builder/data-stores/demo-gmail-datastore_1763851937069_google_mail?project=${PROJECT_ID}"
echo ""
echo "2. Calendar Datastore:"
echo "   https://console.cloud.google.com/gen-app-builder/data-stores/demo-calendar-datastore_1763851980966_google_calendar?project=${PROJECT_ID}"
echo ""
echo "3. Drive Datastore:"
echo "   https://console.cloud.google.com/gen-app-builder/data-stores/demo-drive-datastore_1763851832394_google_drive?project=${PROJECT_ID}"
echo ""
echo "=================================="
echo "What to Check:"
echo "=================================="
echo ""
echo "For each datastore, check:"
echo "  1. Document count (should be > 0)"
echo "  2. Data connectors tab - are Gmail/Calendar/Drive connected?"
echo "  3. Last sync time - when was data last indexed?"
echo "  4. Status - any errors or warnings?"
echo ""
echo "If data sources are disconnected:"
echo "  - Click 'Add data' or 'Reconnect'"
echo "  - Authenticate with the ge-worker account"
echo "  - Wait for indexing to complete (10min - 24hrs)"
echo ""
